In [2]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [6]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer

In [7]:
df=pd.read_csv('titanic_toy.csv')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Age       714 non-null    float64
 1   Fare      846 non-null    float64
 2   Family    891 non-null    int64
 3   Survived  891 non-null    int64
dtypes: float64(2), int64(2)
memory usage: 28.0 KB

In [9]:
df.head()

    Age     Fare  Family  Survived
0  22.0   7.2500       1         0
1  38.0  71.2833       1         1
2  26.0   7.9250       0         1
3  35.0  53.1000       1         1
4  35.0   8.0500       0         0

In [10]:
df.isnull().mean()

Age         0.198653
Fare        0.050505
Family      0.000000
Survived    0.000000
dtype: float64

In [11]:
X=df.drop(columns=['Survived']) 
y=df['Survived']

In [12]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [13]:
X_train.shape,X_test.shape

((712, 3), (179, 3))

In [16]:
X_train.isnull().mean()

Age       0.207865
Fare      0.050562
Family    0.000000
dtype: float64

X_test.isnull().mean()

In [20]:
mean_age=X_train['Age'].mean()
median_age=X_train['Age'].median()

mean_fare=X_train["Fare"].mean() 
median_fare=X_train["Fare"].median()

In [21]:
X_train['Age_median']=X_train["Age"].fillna(median_age)
X_train['Age_mean'] = X_train['Age'].fillna(mean_age)

In [22]:
X_train['Fare_median'] = X_train['Fare'].fillna(median_fare)
X_train['Fare_mean'] = X_train['Fare'].fillna(mean_fare)

In [24]:
X_train.sample(5)

      Age      Fare  Family  Age_median   Age_mean  Fare_median  Fare_mean
603  44.0    8.0500       0       44.00  44.000000       8.0500     8.0500
815   NaN    0.0000       0       28.75  29.785904       0.0000     0.0000
390  36.0  120.0000       3       36.00  36.000000     120.0000   120.0000
493  71.0   49.5042       0       71.00  71.000000      49.5042    49.5042
651  18.0   23.0000       1       18.00  18.000000      23.0000    23.0000

In [26]:
print('Original Age variable variance: ', X_train['Age'].var())
print('Age Variance after median imputation: ', X_train['Age_median'].var())
print('Age Variance after mean imputation: ', X_train['Age_mean'].var())

print('Original Fare variable variance: ', X_train['Fare'].var())
print('Fare Variance after median imputation: ', X_train['Fare_median'].var())
print('Fare Variance after mean imputation: ', X_train['Fare_mean'].var())

Original Age variable variance:  204.3495133904614
Age Variance after median imputation:  161.9895663346054
Age Variance after mean imputation:  161.81262452718673
Original Fare variable variance:  2448.197913706318
Fare Variance after median imputation:  2340.0910219753637
Fare Variance after mean imputation:  2324.2385256705547