In [1]:
import numpy as np 
import pandas as pd

In [2]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder

In [3]:
df=pd.read_csv('covid_toy.csv')

In [4]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [6]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2)

In [7]:
X_train

    age  gender  fever   cough       city
53   83    Male   98.0    Mild      Delhi
62   56  Female  104.0  Strong  Bangalore
67   65    Male   99.0    Mild  Bangalore
35   82  Female  102.0  Strong  Bangalore
2    42    Male  101.0    Mild      Delhi
..  ...     ...    ...     ...        ...
23   80  Female   98.0    Mild      Delhi
76   80    Male  100.0    Mild  Bangalore
99   10  Female   98.0  Strong    Kolkata
96   51  Female  101.0  Strong    Kolkata
34   74    Male  102.0    Mild     Mumbai

[80 rows x 5 columns]

# 1.Aam zindagi

In [9]:
#addinf simple imputer to fever col
si=SimpleImputer()
X_train_fever=si.fit_transform(X_train[['fever']])

# also the test data 

X_test_fever=si.fit_transform(X_test[['fever']])

X_train_fever.shape

(80, 1)

In [12]:
# ordinalenconding -> cough
oe=OrdinalEncoder(categories=[['Mild','Strong']])
X_train_cough=oe.fit_transform(X_train[['cough']]) 

#also the test data set
X_test_cough=oe.fit_transform(X_test[['cough']]) 
X_train_cough.shape

(80, 1)

In [14]:
# OneHotencoding -> Gender,city

ohe=OneHotEncoder(drop='first') 
X_train_gender_city=ohe.fit_transform(X_train[['gender','city']]) 

#also the test data

X_test_gender_city=ohe.fit_transform(X_test[['gender','city']]) 
X_train_gender_city.shape

(80, 4)

In [19]:
# extracting age
X_train_age = X_train.drop(columns=['gender', 'fever', 'cough', 'city']).values 
# Note: Changed from [['gender','fever','cough','city']] to ['gender','fever','cough','city']
# The double brackets were causing the error

# also the test data
X_test_age = X_test.drop(columns=['gender', 'fever', 'cough', 'city']).values

X_train_age.shape

(80, 1)

# 2.COLUMN TRANSFORMER

In [21]:
from sklearn.compose import ColumnTransformer

In [23]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),  # Fixed the parentheses here
    ('tnf3', OneHotEncoder(drop='first'), ['gender', 'city'])
], remainder='passthrough')

In [24]:
transformer.fit_transform(X_train).shape

(80, 7)

In [25]:
transformer.fit_transform(X_test)

array([[100.        ,   1.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  47.        ],
       [101.11764706,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  34.        ],
       [101.11764706,   1.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  20.        ],
       [ 98.        ,   1.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  34.        ],
       [ 98.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  40.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [104.        ,   0.        ,   0.        ,   0.        ,
          1.        ,   0.        ,   6.        ],
       [101.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  34.        ],
       [100.        ,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  27.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   1.        ,  42.        ],
       [102.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   0.        ,  69.        ],
       [ 99.        ,   0.        ,   0.        ,   0.        ,
          0.        ,   1.        ,  14.        ],
       [101.        ,   1.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  14.        ],
       [102.        ,   1.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  20.        ],
       [104.        ,   1.        ,   0.        ,   1.        ,
          0.        ,   0.        ,  34.        ],
       [101.11764706,   0.        ,   1.        ,   1.        ,
          0.        ,   0.        ,  38.        ],
       [ 99.        ,   1.        ,   0.        ,   0.        ,
          1.        ,   0.        ,  25.        ],
       [103.        ,   0.        ,   1.        ,   0.        ,
          1.        ,   0.        ,  83.        ],
       [100.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  10.        ],
       [104.        ,   0.        ,   1.        ,   0.        ,
          0.        ,   0.        ,  51.        ]])