In [5]:
import pandas as pd 
import seaborn as sns
import numpy as np

In [6]:
df=pd.read_csv('customer.csv')

In [7]:
df.sample(5)

    age  gender review education purchased
15   75    Male   Poor        UG        No
45   61    Male   Poor        PG       Yes
7    60  Female   Poor    School       Yes
17   22  Female   Poor        UG       Yes
41   23    Male   Good        PG       Yes

In [9]:
df=df.iloc[:,2:]

In [11]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size=0.2)

In [15]:
X_train

     review education
6      Good    School
35     Poor    School
49     Good        UG
25     Good    School
2      Good        PG
3      Good        PG
43     Poor        PG
48     Good        UG
21  Average        PG
33     Good        PG
17     Poor        UG
27     Poor        PG
7      Poor    School
14     Poor        PG
13  Average    School
41     Good        PG
44  Average        UG
30  Average        UG
34  Average    School
32  Average        UG
24  Average        PG
4   Average        UG
46     Poor        PG
20  Average    School
0   Average    School
5   Average    School
1      Poor        UG
39     Poor        PG
12     Poor    School
31     Poor    School
9      Good        UG
18     Good    School
19     Poor        PG
29  Average        UG
22     Poor        PG
16     Poor        UG
38     Good    School
15     Poor        UG
47     Good        PG
11     Good        UG

In [31]:
from sklearn.preprocessing import OrdinalEncoder

oe=OrdinalEncoder(categories=[['Poor','Average','Good'],['School','UG','PG']])

In [33]:
oe.fit(X_train)

ValueError: could not convert string to float: 'Poor'